### ISSUE TITLE
Exception while sending ping.

### ISSUE THREAD

**Issue by krishnavelu** [krishnavelu/alice_blue#10]
Getting exception while sending ping. Need to check if websocket is open, then send.

```
09:18:33.900.682, Subscribe, WARNING, Alice Websocket is in error - error Connection is already closed.
09:18:33.901.022, Subscribe, WARNING, Alice Websocket closed
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/krishna/PTrade/broker_alice/alice_blue/alice_blue/alice_blue.py", line 358, in __send_heartbeat
    self.__websocket.send(json.dumps(heart_beat), opcode = websocket._abnf.ABNF.OPCODE_PING)
  File "/home/krishna/.local/lib/python3.7/site-packages/websocket/_app.py", line 153, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/home/krishna/.local/lib/python3.7/site-packages/websocket/_core.py", line 253, in send
    return self.send_frame(frame)
  File "/home/krishna/.local/lib/python3.7/site-packages/websocket/_core.py", line 278, in send_frame
    l = self._send(data)
  File "/home/krishna/.local/lib/python3.7/site-packages/websocket/_core.py", line 448, in _send
    return send(self.sock, data)
  File "/home/krishna/.local/lib/python3.7/site-packages/websocket/_socket.py", line 135, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.
```

**Comment by krishnavelu** [comment]
This got fixed along with issue #9
