### ISSUE TITLE
Querying order history sometimes throws an exception 

### ISSUE THREAD

**Issue by Deepak19995** [krishnavelu/alice_blue#141]
Hello Krishnavelu,

I am using algo trading via alice blue and a piece of logic sometimes thorws exception and sometimes works normal. The exception is caused when I try to access my order history and most of the times the pending orders in particular. The line in code looks like this:

oms_order_id = [position['oms_order_id'] for position in alice.get_order_history()['data']['pending_orders'] if ((position['trading_symbol'] == i) and ((position['order_type'] == 'SL-M') or (position['order_type'] == 'LIMIT')))]

The error thrown looks like this:
C:\myapp\successful_algos>python c:/myapp/successful_algos/squeeze_mis.py
Traceback (most recent call last):
  File "c:/myapp/successful_algos/squeeze_mis.py", line 420, in <module>
    getdetailsofstocksfromchartinkandbuy()
  File "c:/myapp/successful_algos/squeeze_mis.py", line 116, in getdetailsofstocksfromchartinkandbuy
    getdetailsofopenstocksinporfolio()
  File "c:/myapp/successful_algos/squeeze_mis.py", line 65, in getdetailsofopenstocksinporfolio
    results = alice.get_daywise_positions()
  File "C:\Users\i327661\AppData\Local\Programs\Python\Python38-32\lib\site-packages\alice_blue\alice_blue.py", line 429, in get_daywise_positions
    return self.__api_call_helper('positions_daywise', Requests.GET, None, None)
  File "C:\Users\i327661\AppData\Local\Programs\Python\Python38-32\lib\site-packages\alice_blue\alice_blue.py", line 854, in __api_call_helper
    raise requests.HTTPError(response.text)
requests.exceptions.HTTPError: {"status":"error","message":"Request Unauthorised","data":{}}

OR EVEN LIKE THIS

SRTRANSFIN-EQ
Traceback (most recent call last):
  File "c:/myapp/successful_algos/squeeze_mis.py", line 424, in <module>
    cancelotherorderornot()
  File "c:/myapp/successful_algos/squeeze_mis.py", line 277, in cancelotherorderornot
    oms_order_id = [position['oms_order_id'] for position in alice.get_order_history()['data']['pending_orders'] if ((position['trading_symbol'] == i) and ((position['order_type'] == 'SL-M') or (position['order_type'] == 'LIMIT')))]
  File "C:\Users\i327661\AppData\Local\Programs\Python\Python38-32\lib\site-packages\alice_blue\alice_blue.py", line 440, in get_order_history
    return self.__api_call_helper('get_orders', Requests.GET, None, None);
  File "C:\Users\i327661\AppData\Local\Programs\Python\Python38-32\lib\site-packages\alice_blue\alice_blue.py", line 854, in __api_call_helper
    raise requests.HTTPError(response.text)
requests.exceptions.HTTPError: {"status":"error","message":"Request Unauthorised","data":{}}

OR EVEN LIKE THIS
C:\myapp\successful_algos>python c:/myapp/successful_algos/squeeze_mis.py
Traceback (most recent call last):
  File "c:/myapp/successful_algos/squeeze_mis.py", line 420, in <module>
    getdetailsofstocksfromchartinkandbuy()
  File "c:/myapp/successful_algos/squeeze_mis.py", line 116, in getdetailsofstocksfromchartinkandbuy
    getdetailsofopenstocksinporfolio()
  File "c:/myapp/successful_algos/squeeze_mis.py", line 75, in getdetailsofopenstocksinporfolio
    porfList1 = [position['trading_symbol'] for position in alice.get_order_history()['data']['pending_orders']]
KeyError: 'pending_orders'
Please note these same lines work normally at times and at times throw issue, kindly let me know if this is expected behaviour so that I can add exception handling or is it an issue.
One more strange thing I noticed is that the alice object works fine even with my old password, I thought it has something to do with password set my old password and alice object gets created with old credentials as well but even then the above issue persists at times!!
Please help

Best Regards,
DK

**Comment by krishnavelu** [comment]
Read [this](https://gist.github.com/krishnavelu/e0df312ccf5f022edb1823461ff4230e) before you creat an issue. Follow these steps while creating an issue.

**Comment by PranavSonar** [comment]
I am also getting same error.

relevant code:

`response = alice.get_order_history(orderID)
  File "alice_blue.py", line 481, in get_order_history
    return self.__api_call_helper('get_order_info', Requests.GET, {'order_id': order_id}, None);
  File "alice_blue.py", line 956, in __api_call_helper
    raise requests.HTTPError(response.text)
requests.exceptions.HTTPError: {"status":"error","message":"Request Unauthorised","data":{}}`

Is this because i logged in mobile app just before above query execute? Do you think mobile app and ant web has any role in expiring generated token?

**Comment by jaydave1988** [comment]
Issue is already opened #139 
And I dont think so it is because of login through moblie.

**Comment by krishnavelu** [comment]
This is a duplicate one, so closing this. #139 will be open till that problem is solved.
