### ISSUE TITLE
getting multiple error

### ISSUE THREAD

**Issue by sekhartuku** [krishnavelu/alice_blue#265]
HI sir i am getting the following error.. 

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ant.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth2/auth?response_type=code&state=test_state&client_id=AB127547&redirect_uri=https://ant.aliceblueonline.com/plugin/callback HTTP/1.1" 302 0
DEBUG:urllib3.connectionpool:https://ant.aliceblueonline.com:443 "GET /oauth2/fallbacks/error?error=invalid_client&error_description=Client+authentication+failed+%28e.g.%2C+unknown+client%2C+no+client+authentication+included%2C+or+unsupported+authentication+method%29&error_hint=The+requested+OAuth+2.0+Client+does+not+exist. HTTP/1.1" 200 None
ERROR:alice_blue.alice_blue:OAuth 2.0 Error occurred. Please verify your api_secret
Traceback (most recent call last):
  File "C:\Users\Himansu\AppData\Local\Programs\Python\Python39\lib\site-packages\alice_blue\alice_blue.py", line 208, in __init__
    profile = self.get_profile()
  File "C:\Users\Himansu\AppData\Local\Programs\Python\Python39\lib\site-packages\alice_blue\alice_blue.py", line 445, in get_profile
    profile = self.__api_call_helper('profile', Requests.GET, None, None)
  File "C:\Users\Himansu\AppData\Local\Programs\Python\Python39\lib\site-packages\alice_blue\alice_blue.py", line 945, in __api_call_helper
    response = self.__api_call(url, http_method, data)
  File "C:\Users\Himansu\AppData\Local\Programs\Python\Python39\lib\site-packages\alice_blue\alice_blue.py", line 953, in __api_call
    if(len(self.__access_token) > 100):
TypeError: object of type 'NoneType' has no len()

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Himansu\Desktop\test.py", line 17, in <module>
    alice = AliceBlue(username=username, password=password, access_token=access_token, master_contracts_to_download=['NSE'])
  File "C:\Users\Himansu\AppData\Local\Programs\Python\Python39\lib\site-packages\alice_blue\alice_blue.py", line 210, in __init__
    raise Exception(f"Couldn't get profile info with credentials provided '{e}'")
Exception: Couldn't get profile info with credentials provided 'object of type 'NoneType' has no len()'

***Repl Closed***

**Comment by krishnavelu** [comment]
Read and follow [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) before creating a new issue.
