### ISSUE TITLE
Couldn't get profile info with credentials provided Error

### ISSUE THREAD

**Issue by keerthankumar** [krishnavelu/alice_blue#271]
getting below error, was working till yesterday

```
Traceback (most recent call last):
  File "C:\Users\keerthan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\alice_blue\alice_blue.py", line 208, in __init__
    profile = self.get_profile()
  File "C:\Users\keerthan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\alice_blue\alice_blue.py", line 445, in get_profile
    profile = self.__api_call_helper('profile', Requests.GET, None, None)
  File "C:\Users\keerthan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\alice_blue\alice_blue.py", line 949, in __api_call_helper
    raise requests.HTTPError(response.text)
requests.exceptions.HTTPError: {"status":"error","message":"Request Unauthorised","data":{}}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:/gitlab/one_algo/statergy/stock_trend-autotraderweb/scripts/create_database_aliceblue.py", line 191, in <module>
    alice = AliceBlue(username=username, password=password, access_token=session_code)
  File "C:\Users\keerthan\AppData\Local\Programs\Python\Python38-32\lib\site-packages\alice_blue\alice_blue.py", line 210, in __init__
    raise Exception(f"Couldn't get profile info with credentials provided '{e}'")
Exception: Couldn't get profile info with credentials provided '{"status":"error","message":"Request Unauthorised","data":{}}'  
```

**Comment by keerthankumar** [comment]
this was mistake from my end, sorry closing the issue
