### ISSUE TITLE
unable to run aliceblue code with PYCHARM (2021.2.4 version ) on windows

### ISSUE THREAD

**Issue by bhvarshn** [krishnavelu/alice_blue#390]
Getting below error with PYCHARM (2021.2.4 version ) on windows

C:\Users\bhvarshn\PycharmProjects\pythonProject1\venv\Scripts\python.exe "C:/Users/bhvarshn/PycharmProjects/pythonProject1/My Project/Alicebluetrading/aliceblueexcelcode.py"
Traceback (most recent call last):
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject1\My Project\Alicebluetrading\aliceblueexcelcode.py", line 4, in <module>
    from alice_blue import *
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject1\venv\lib\site-packages\alice_blue\__init__.py", line 1, in <module>
    from .alice_blue import AliceBlue, TransactionType, OrderType, ProductType, LiveFeedType, Instrument
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject1\venv\lib\site-packages\alice_blue\alice_blue.py", line 11, in <module>
    from protlib import CUInt, CStruct, CULong, CUChar, CArray, CUShort, CString
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject1\venv\lib\site-packages\protlib.py", line 220
    raise CError, cerror, tb
                ^
SyntaxError: invalid syntax

Process finished with exit code 1

**Comment by krishnavelu** [comment]
Read the example and try that first. Then do small modifications.

**Comment by bhvarshn** [comment]
Protlib library is not compatible with python 3

**Comment by krishnavelu** [comment]
https://pypi.org/project/protlib/

<img width="399" alt="image" src="https://user-images.githubusercontent.com/38440742/161517023-7dc74304-e5bd-440f-8e25-e91aa7d918c6.png">

**Comment by bhvarshn** [comment]
aliceblue code is not able to download live data with python 3 and pycharm version (2021.2.4 version ) on windows. i fixed below errors of protlib by correcting syntax . With corrected syntax , error is not coming but no NSE data is getting loaded. 
Same code of mine is working fine with old python and pycharm version. Please help 

C:\Users\bhvarshn\PycharmProjects\pythonProject1\venv\Scripts\python.exe "C:/Users/bhvarshn/PycharmProjects/pythonProject1/My Project/Alicebluetrading/aliceblueexcelcode.py"
Traceback (most recent call last):
File "C:\Users\bhvarshn\PycharmProjects\pythonProject1\My Project\Alicebluetrading\aliceblueexcelcode.py", line 4, in
from alice_blue import *
File "C:\Users\bhvarshn\PycharmProjects\pythonProject1\venv\lib\site-packages\alice_blue_init_.py", line 1, in
from .alice_blue import AliceBlue, TransactionType, OrderType, ProductType, LiveFeedType, Instrument
File "C:\Users\bhvarshn\PycharmProjects\pythonProject1\venv\lib\site-packages\alice_blue\alice_blue.py", line 11, in
from protlib import CUInt, CStruct, CULong, CUChar, CArray, CUShort, CString
File "C:\Users\bhvarshn\PycharmProjects\pythonProject1\venv\lib\site-packages\protlib.py", line 220
raise CError, cerror, tb
^
SyntaxError: invalid syntax

**Comment by krishnavelu** [comment]
you said you fixed the protlib syntax. Now what's the problem?  The error you've shown is about protlib syntax error.

**Comment by krishnavelu** [comment]
use python 3.9. protlib has issue with Python 3.10.

https://github.com/EliAndrewC/protlib/issues/2

**Comment by bhvarshn** [comment]
after correcting syntax , not able to download live data from Alice blue . same code is working with older version of pycharm with old protlib

**Comment by krishnavelu** [comment]
use old version

**Comment by bhvarshn** [comment]
Even with python 3.9.0 below error is coming 

C:\Users\bhvarshn\PycharmProjects\pythonProject\venv\Scripts\python.exe C:/Users/bhvarshn/PycharmProjects/pythonProject/Alicebluetrading/first5mincode.py
Traceback (most recent call last):
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject\Alicebluetrading\first5mincode.py", line 1, in <module>
    from alice_blue import *
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject\venv\lib\site-packages\alice_blue\__init__.py", line 1, in <module>
    from .alice_blue import AliceBlue, TransactionType, OrderType, ProductType, LiveFeedType, Instrument
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject\venv\lib\site-packages\alice_blue\alice_blue.py", line 11, in <module>
    from protlib import CUInt, CStruct, CULong, CUChar, CArray, CUShort, CString
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject\venv\lib\site-packages\protlib.py", line 220
    raise CError, cerror, tb
                ^
SyntaxError: invalid syntax

Process finished with exit code 1

C:\Users\bhvarshn\PycharmProjects\pythonProject> python                
Python 3.9.0 (tags/v3.9.0:9cf6752, Oct  5 2020, 15:34:40) [MSC v.1927 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>

Please fix this issue asap as it has been ongoing for couple of days . Also if i correct the protlib syntax , Aliceblue api not able to download live data. Please check at your end asap and fix it . thanks

**Comment by bhvarshn** [comment]
issue fixed with PS C:\Users\bhvarshn\PycharmProjects\pythonProject> python
Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:43:08) [MSC v.1926 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
Thanks

**Comment by krishnavelu** [comment]
Issue resolved. Try the newest version.
