### ISSUE TITLE
aliceblue api frequent disconnect with below error

### ISSUE THREAD

**Issue by bhvarshn** [krishnavelu/alice_blue#394]
Hi getting this error while running this program . Code abnormally terminates frequently 

Traceback (most recent call last):
  File "C:/Users/bhvarshn/PycharmProjects/pythonProject/My Project/alicebluetrading4thapril/aliceblueexcelcode - [4thapril.py]()", line 209, in <module>
    main()
  File "C:/Users/bhvarshn/PycharmProjects/pythonProject/My Project/alicebluetrading4thapril/aliceblueexcelcode - [4thapril.py]()", line 76, in main
    alice.subscribe(instrument, LiveFeedType.MARKET_DATA)
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject\My Project\venv\lib\site-packages\alice_blue\alice_[blue.py]()", line 761, in subscribe
    return self.__ws_send(data)
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject\My Project\venv\lib\site-packages\alice_blue\alice_[blue.py]()", line 403, in __ws_send
    ret = self.__websocket.send(*args, **kwargs)
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject\My Project\venv\lib\site-packages\websocket\_[app.py]()", line 191, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject\My Project\venv\lib\site-packages\websocket\_[core.py]()", line 282, in send
    return self.send_frame(frame)
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject\My Project\venv\lib\site-packages\websocket\_[core.py]()", line 310, in send_frame
    l = self._send(data)
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject\My Project\venv\lib\site-packages\websocket\_[core.py]()", line 514, in _send
    return send(self.sock, data)
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject\My Project\venv\lib\site-packages\websocket\_[socket.py]()", line 175, in send
    return _send()
  File "C:\Users\bhvarshn\PycharmProjects\pythonProject\My Project\venv\lib\site-packages\websocket\_[socket.py]()", line 152, in _send
    return sock.send(data)
  File "C:\Users\bhvarshn\AppData\Local\Programs\Python\Python38-32\lib\[ssl.py]()", line 1173, in send
    return self._sslobj.write(data)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

**Comment by krishnavelu** [comment]
Read [this](https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue) and follow before creating a new issue...

**Comment by bhvarshn** [comment]
what help above link is giving. Be specific what info you need to debug this issue

**Comment by krishnavelu** [comment]
I already mentioned what I need here. 
https://github.com/krishnavelu/alice_blue#read-this-before-creating-an-issue
