### ISSUE TITLE
Getting KeyError: 'userSession'

### ISSUE THREAD

**Issue by Lolxtimes** [krishnavelu/alice_blue#461]
Hi @krishnavelu 
As mentioned in the Issue#440 i have added "checksum=checksum.decode("utf-8")" in line 202 and this is the error i'm getting and not able to create a session ID.
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): a3.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://a3.aliceblueonline.com:443 "POST /rest/AliceBlueAPIService/customer/getEncryptionKey HTTP/1.1" 200 113
INFO:root:Get Encryption Key response {"userId":null,"userData":null,"encKey":"M9XHJGSTJG0Q","apikey":null,"stat":null,"emsg":null,"loginType":null,"version":null,"login":false}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): a3.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://a3.aliceblueonline.com:443 "POST /rest/AliceBlueAPIService/customer/webLogin HTTP/1.1" 200 None
INFO:root:Web Login response {"userId":"AB117607","accountId":null,"password":null,"newPassword":null,"oldPassword":null,"userSessionID":null,"userToken":null,"publicKey4":null,"stringPkey4":null,"publicKey3":null,"stringPkey3":null,"privatekey2":null,"stringPK2":null,"tomcatcount":null,"stat":"Ok","tdata":"Answer the questions","sQuestions":"Year Of Birth","sCount":"1","sIndex":"1","ques_Ans":null,"answer1":null,"answer2":null,"sUserToken":null,"sPasswordReset":null,"message":null,"exch":null,"symbol":null,"mwName":null,"email":null,"pan":null,"list":null,"preLogin":null,"userSettingDto":null,"is_mob":false,"dob":null,"scripList":null,"validAnsResponse":null,"webSocketID":null,"authorizationStatus":0,"expiryDate":0,"userApiKey":null,"vendorId":0,"vendorApiKey":null,"vendorSecret":null,"deviceId":null,"loginType":null,"callBackUrl":null,"loginMode":null,"vendor":null,"authCode":null,"version":null,"checkSum":null,"emsg":null,"v2":false}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): a3.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://a3.aliceblueonline.com:443 "POST /rest/AliceBlueAPIService/sso/validAnswer HTTP/1.1" 200 1193
INFO:root:Web Login 2FA response {"stat":"Ok","isAuthorized":true,"redirectUrl":"https://ant.aliceblueonline.com/plugin/callback?authCode=7YH1639OUMP8GUWLJM5D&userId=AB117607","loginResponse":{"userId":"AB117607","accountId":null,"password":null,"newPassword":null,"oldPassword":null,"userSessionID":"l8diYJgVLi99qW7oudNGnZ8Bsk9ZCyIHmaNx7rYKJQoyLg7dmEgZSKxjylcRaBdJ2nGNyYIlW4SImfPi8EFNxrY5oOtHkCxVMLYtU1ShGkK6QSTtPrzD984N1ULBJixdeyUXXtudG8OUeamEJnv3nkX4V7R9fTR1mxza9AXOgVjfIPr7vlSkojZnkcqTP4QJGGOpqeXRKjUEscCmHxMnXz0gKubGpUEERTsymHJJWvXAPtQZjoC4xxzOBrgFmjIX","userToken":null,"publicKey4":null,"stringPkey4":null,"publicKey3":null,"stringPkey3":null,"privatekey2":null,"stringPK2":null,"tomcatcount":null,"stat":"Ok","tdata":"OK","sQuestions":null,"sCount":null,"sIndex":null,"ques_Ans":null,"answer1":null,"answer2":null,"sUserToken":null,"sPasswordReset":"N","message":"NO_DATA","exch":null,"symbol":null,"mwName":null,"email":null,"pan":null,"list":null,"preLogin":null,"userSettingDto":{"stat_DFlogin":null,"exch":["BCD","BSE","CDS","MCX","NSE","NFO"],"prctyp":["SL-M","SL","MKT","L"],"pCode":["CNC","NRML","MIS","CO"],"s_prdt_ali":"CNC:CNC||NRML:NRML||MIS:MIS||CO:CO","sTransFlg":"YES","default_market_watch_name":null,"broker_name":"ALICEBLUE","branch_id":"HO","market_watch_count":"30","email":"vnhegde71@gmail.com","weblink":"NO DATA","account_id":"AB117607","exchDeatil":{"CURRENCY":[{"product":["NRML","MIS"],"exchseg":"bcs_fo","exch":"BCD"},{"product":["NRML","MIS","CO"],"exchseg":"cde_fo","exch":"CDS"}],"DERIVATIVE":[{"product":["NRML","MIS","CO"],"exchseg":"nse_fo","exch":"NFO"}],"COMMODITY":[{"product":["NRML","MIS","CO"],"exchseg":"mcx_fo","exch":"MCX"}],"EQUITY":[{"product":["CNC","MIS","CO"],"exchseg":"bse_cm","exch":"BSE"},{"product":["CNC","MIS","CO"],"exchseg":"nse_cm","exch":"NSE"}]},"lots_weight":"N","password_special_character":"N","accountName":"VEENA NARAYAN HEGDE","userPrivileges":"all","ySXorderEntry":"YES/NO","criteriaAttribute_array":[],"emsg_DFlogin":null},"is_mob":false,"dob":null,"scripList":null,"validAnsResponse":null,"webSocketID":"9362856582","authorizationStatus":0,"expiryDate":0,"userApiKey":null,"vendorId":0,"vendorApiKey":null,"vendorSecret":null,"deviceId":null,"loginType":null,"callBackUrl":null,"loginMode":null,"vendor":null,"authCode":null,"version":null,"checkSum":null,"emsg":null,"v2":false}}
INFO:root:isAuthorized True
INFO:root:authCode 7YH1639OUMP8GUWLJM5D
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): a3.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://a3.aliceblueonline.com:443 "POST /rest/AliceBlueAPIService/api/customer/getAPIEncpkey HTTP/1.1" 200 147
INFO:root:Get API Encryption Key response {"userId":"AB117607","userData":null,"encKey":"CLHJC02G74S5O4HRRA39NLWHCAWMEVMQ","apikey":null,"stat":"Ok","emsg":null,"loginType":null,"version":null,"login":true}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): a3.aliceblueonline.com:443
DEBUG:urllib3.connectionpool:https://a3.aliceblueonline.com:443 "POST /rest/AliceBlueAPIService/sso/getUserDetails HTTP/1.1" 200 44
INFO:root:Session ID response {"emsg":"Invalid auth code","stat":"Not_Ok"}
Traceback (most recent call last):
  File "c:/Amol/python/trial/AliceKrishnavelu.py", line 6, in <module>
    session_id = AliceBlue.login_and_get_sessioID(   username    = "AB117607",
  File "C:\Users\*****\AppData\Local\Programs\Python\Python38-32\lib\site-packages\alice_blue\alice_blue.py", line 232, in login_and_get_sessioID
    session_id = r.json()['userSession']
KeyError: 'userSession'
```

**Comment by krishnavelu** [comment]
You don't need to add manual. Uninstall everything and install the new version 2.0.2

**Comment by Lolxtimes** [comment]
Sorry , i was giving the wrong api key 
The issue has been resolved.
