### ISSUE TITLE
Unable to get access token using login_and_get_sessionID

### ISSUE THREAD

**Issue by sree161** [krishnavelu/alice_blue#469]
Hi ,

Below is my code to get access token.
    access_token = AliceBlue.login_and_get_sessionID(username=Credentials.UserName.value, password=Credentials.PassWord.value, twoFA=Credentials.2sv.value, app_id=Credentials.AppId.value, api_secret=Credentials.SecretKey.value)

It return the below error,
Traceback (most recent call last):
  File "C:\Users\sreek\Downloads\Python\live_data_collector.py", line 207, in <module>
    alice = login()
  File "C:\Users\sreek\Downloads\Python\live_data_collector.py", line 83, in login
    access_token = AliceBlue.login_and_get_sessionID(username=Credentials.UserName.value, password=Credentials.PassWord.value, twoFA='1986', app_id=Credentials.AppId.value, api_secret=Credentials.SecretKey.value)
  File "C:\Users\sreek\Downloads\Python\venv\lib\site-packages\alice_blue\alice_blue.py", line 216, in login_and_get_sessionID
    isAuthorized = r.json()['isAuthorized']
KeyError: 'isAuthorized'

can u please let me know where i'm doing wrong?

**Comment by krishnavelu** [comment]
check your credentials.

**Comment by sree161** [comment]
Sorry for the inconvinence. I changed my password which took sometime to reflect i guess
