### ISSUE TITLE
Error while trying to create AliceBlue object with username and session_id

### ISSUE THREAD

**Issue by Kumar-0** [krishnavelu/alice_blue#479]
Hi @krishnavelu , 

I am able to create session id with my credentials. 
But when trying to create AliceBlue object I am getting the following error. 
I tried searching the forum for similar issue, but didn't find one. 

```
Traceback (most recent call last):
  File "d:\python\apps\hellowworld\demo.py", line 20, in <module>        
    alice = AliceBlue(username=username, session_id=session_id)
  File "C:\Python310\lib\site-packages\alice_blue\alice_blue.py", line 161, in __init__
    self.__get_master_contract(e)
  File "C:\Python310\lib\site-packages\alice_blue\alice_blue.py", line 943, in __get_master_contract
    d = json.loads(fo.read())
  File "C:\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Python310\lib\json\decoder.py", line 355, in raw_decode       
    raise JSONDecodeError("Expecting value", s, err.value) from None     
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
```

**Comment by krishnavelu** [comment]
Try deleting all `alice_blue_master_contract_****.json` file in your temp folder.
