### ISSUE TITLE
Not able to download NFO contracts

### ISSUE THREAD

**Issue by srinidhihebbar260297** [krishnavelu/alice_blue#495]
`session_id = AliceBlue.login_and_get_sessionID(  username    = name, 
                                                    password    = password, 
                                                    twoFA       = two_fa,
                                                    app_id      = app_id,
                                                    api_secret  = app_secret)

alice=AliceBlue(username = name, session_id = session_id, master_contracts_to_download=['NFO'])`

output <alice=AliceBlue(username = name, session_id = session_id, master_contracts_to_download=['NFO'])
Traceback (most recent call last):

  File "C:\Users\RAMAKR~1\AppData\Local\Temp/ipykernel_12304/3008746932.py", line 1, in <module>
    alice=AliceBlue(username = name, session_id = session_id, master_contracts_to_download=['NFO'])

  File "C:\ProgramData\Anaconda3\lib\site-packages\alice_blue\alice_blue.py", line 164, in __init__
    self.__get_master_contract(e)

  File "C:\ProgramData\Anaconda3\lib\site-packages\alice_blue\alice_blue.py", line 943, in __get_master_contract
    d = json.loads(fo.read())

  File "C:\ProgramData\Anaconda3\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)

  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())

  File "C:\ProgramData\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None

JSONDecodeError: Expecting value>

**Comment by krishnavelu** [comment]
Retry during market time.

**Comment by srinidhihebbar260297** [comment]
Oh Thank you, that is where I was wrong!! I was trying in midnight to place orders for the last 3 years and did not realize that the market has to be open.

**Comment by krishnavelu** [comment]
Closing as your issue is resolved. Reopen if needed.
