### ISSUE TITLE
Websocket closes abruptly and live feed of banknifty stops

### ISSUE THREAD

**Issue by PythonNovice5** [krishnavelu/alice_blue#507]
Hi, 

I am streaming Banknifty to take trades in the live market using Websocket. Sometimes it closes even though I am trying to handle the exception. Below are the error details. Can someone please help? @krishnavelu

> Traceback (most recent call last):
  File "/home/angel/bankniftytrading/Login_alice.py", line 64, in <module>
    alice.subscribe(alice.get_instrument_by_token('NSE', '26009'), LiveFeedType.TICK_DATA)
  File "/home/angel/.local/lib/python3.6/site-packages/alice_blue/alice_blue.py", line 759, in subscribe
    self.__ws_send(data)
  File "/home/angel/.local/lib/python3.6/site-packages/alice_blue/alice_blue.py", line 472, in __ws_send
    self.__websocket.send(json.dumps(data))
  File "/home/angel/.local/lib/python3.6/site-packages/websocket/_app.py", line 191, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/home/angel/.local/lib/python3.6/site-packages/websocket/_core.py", line 282, in send
    return self.send_frame(frame)
  File "/home/angel/.local/lib/python3.6/site-packages/websocket/_core.py", line 310, in send_frame
    l = self._send(data)
  File "/home/angel/.local/lib/python3.6/site-packages/websocket/_core.py", line 514, in _send
    return send(self.sock, data)
  File "/home/angel/.local/lib/python3.6/site-packages/websocket/_socket.py", line 175, in send
    return _send()
  File "/home/angel/.local/lib/python3.6/site-packages/websocket/_socket.py", line 152, in _send
    return sock.send(data)
  File "/usr/lib/python3.6/ssl.py", line 946, in send
    return socket.send(self, data, flags)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/angel/bankniftytrading/Login_alice.py", line 71, in <module>
    alice.subscribe(alice.get_instrument_by_token('NSE', '26009'), LiveFeedType.TICK_DATA)
  File "/home/angel/.local/lib/python3.6/site-packages/alice_blue/alice_blue.py", line 759, in subscribe
    self.__ws_send(data)
  File "/home/angel/.local/lib/python3.6/site-packages/alice_blue/alice_blue.py", line 472, in __ws_send
    self.__websocket.send(json.dumps(data))
  File "/home/angel/.local/lib/python3.6/site-packages/websocket/_app.py", line 191, in send
    if not self.sock or self.sock.send(data, opcode) == 0:
  File "/home/angel/.local/lib/python3.6/site-packages/websocket/_core.py", line 282, in send
    return self.send_frame(frame)
  File "/home/angel/.local/lib/python3.6/site-packages/websocket/_core.py", line 310, in send_frame
    l = self._send(data)
  File "/home/angel/.local/lib/python3.6/site-packages/websocket/_core.py", line 514, in _send
    return send(self.sock, data)
  File "/home/angel/.local/lib/python3.6/site-packages/websocket/_socket.py", line 148, in send
    raise WebSocketConnectionClosedException("socket is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: socket is already closed.

**Comment by krishnavelu** [comment]
Check you internet connection.
